#!/usr/bin/env bash
# COI-105: fail-closed [package].coil engine range on install/add/update.
# Pins: omitted / >=0.1.0 succeed; >=0.2.0 and ^0.2 fail before fetch/link.
# Hooks stay off (COI-227); this only asserts they do not fire.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COIL_BIN="${COIL:-coil}"
CACHE="$ROOT/scratch/cache_engine"
BASE="$ROOT/scratch/engine"

if [[ ! -x "$COIL_BIN" ]]; then
  if ! command -v "$COIL_BIN" >/dev/null 2>&1; then
    echo "smoke_engine: coil not found (set COIL)" >&2
    exit 1
  fi
fi

if ! VER_LINE="$("$COIL_BIN" --version)"; then
  echo "smoke_engine: coil --version required" >&2
  exit 1
fi
COIL_VER="${VER_LINE#coil }"
COIL_VER="${COIL_VER%%[$'\n\r']}"
if [[ -z "$COIL_VER" ]]; then
  echo "smoke_engine: could not parse coil --version ($VER_LINE)" >&2
  exit 1
fi

rm -rf "$CACHE" "$BASE"
mkdir -p "$BASE"

plant_hooks() {
  local dest="$1"
  mkdir -p "$dest/hooks"
  cat > "$dest/hooks/preinstall.sh" <<'EOS'
#!/bin/sh
touch "${SPOOL_PROJECT:-.}/HOOK_RAN"
EOS
  cat > "$dest/hooks/include.sh" <<'EOS'
#!/bin/sh
touch "${SPOOL_PROJECT:-.}/HOOK_RAN"
EOS
  chmod +x "$dest/hooks/preinstall.sh" "$dest/hooks/include.sh"
}

write_app() {
  local dest="$1"
  local name="$2"
  local coil_line="${3:-}"
  rm -rf "$dest"
  mkdir -p "$dest/src"
  plant_hooks "$dest"
  cat > "$dest/coil.toml" <<EOF
[package]
name = "$name"
version = "0.0.1"
${coil_line}
include = "./hooks/include.sh"

[module]
roots = ["./src"]
[env]
allow_exec = true

[scripts]
preinstall = "./hooks/preinstall.sh"
postinstall = "./hooks/preinstall.sh"
preupdate = "./hooks/preinstall.sh"
postupdate = "./hooks/preinstall.sh"
EOF
  echo "// app" > "$dest/src/main.hy"
}

write_lib() {
  local dest="$1"
  local name="$2"
  local coil_line="${3:-}"
  rm -rf "$dest"
  mkdir -p "$dest/src"
  plant_hooks "$dest"
  cat > "$dest/coil.toml" <<EOF
[package]
name = "$name"
version = "1.0.0"
${coil_line}
include = "./hooks/include.sh"
[module]
roots = ["./src"]
EOF
  echo "// lib" > "$dest/src/lib.hy"
}

expect_fail() {
  local out="$1"
  local rc="$2"
  local pkg="$3"
  local range="$4"
  if [[ "$rc" -eq 0 ]]; then
    echo "smoke_engine: expected engine range to fail for $pkg" >&2
    echo "$out" >&2
    exit 1
  fi
  echo "$out" | grep -q "package $pkg"
  echo "$out" | grep -q "$range"
  echo "$out" | grep -q "$COIL_VER"
}

assert_hooks_idle() {
  local proj="${1:-$SPOOL_PROJECT}"
  if [[ -f "$proj/HOOK_RAN" ]]; then
    echo "smoke_engine: hook ran as a side effect ($proj/HOOK_RAN)" >&2
    exit 1
  fi
}

assert_not_linked() {
  local proj="${1:-$SPOOL_PROJECT}"
  if [[ -d "$proj/.spool/deps" ]]; then
    echo "smoke_engine: linked .spool/deps before failing" >&2
    exit 1
  fi
}

assert_no_fetch() {
  local proj="${1:-$SPOOL_PROJECT}"
  if [[ -d "$CACHE/git" ]]; then
    echo "smoke_engine: unsatisfied range fetched before failing" >&2
    exit 1
  fi
  if [[ -f "$proj/.spool/fetch.sh" ]]; then
    echo "smoke_engine: wrote fetch.sh before failing" >&2
    exit 1
  fi
  if [[ -f "$proj/.spool/tags.tsv" ]]; then
    echo "smoke_engine: resolved tags before failing" >&2
    exit 1
  fi
  if [[ -f "$proj/.spool/resolve.sh" ]]; then
    echo "smoke_engine: wrote resolve.sh before failing" >&2
    exit 1
  fi
  assert_not_linked "$proj"
}

export COIL="$COIL_BIN"
export COIL_CACHE_DIR="$CACHE"

# Path lib with no engine constraint (success-path add).
OKLIB="$BASE/oklib"
write_lib "$OKLIB" "oklib"

# Omitted key: install / add succeed.
OMIT="$BASE/omit"
write_app "$OMIT" "omit"
export SPOOL_PROJECT="$OMIT"
"$ROOT/spool" install
assert_hooks_idle
"$ROOT/spool" add oklib --path "$OKLIB"
test -L "$OMIT/.spool/deps/oklib"
assert_hooks_idle

# In-range for coil 0.1.0: no-op success on install / add.
OK="$BASE/ok"
write_app "$OK" "ok" "coil = \">=0.1.0\""
export SPOOL_PROJECT="$OK"
"$ROOT/spool" install
assert_hooks_idle
"$ROOT/spool" add oklib --path "$OKLIB"
test -L "$OK/.spool/deps/oklib"
assert_hooks_idle

STAR="$BASE/star"
write_app "$STAR" "star" "coil = \"*\""
export SPOOL_PROJECT="$STAR"
"$ROOT/spool" install
assert_hooks_idle

# Git fixture for fail-closed-before-fetch and in-range update.
FIX="$BASE/fixture"
write_lib "$FIX" "fixture"
git init -q "$FIX"
git -C "$FIX" config user.email "spool@test"
git -C "$FIX" config user.name "spool"
git -C "$FIX" add -A
git -C "$FIX" commit -q -m "init"
git -C "$FIX" tag v1.0.0
REV="$(git -C "$FIX" rev-parse HEAD)"
TREE="$(git -C "$FIX" rev-parse 'HEAD^{tree}')"
URL="file://$FIX"

lock_fixture() {
  local dest="$1"
  cat >> "$dest/coil.toml" <<EOF
[dependencies]
fixture = { git = "$URL", version = "^1.0" }
EOF
  cat > "$dest/coil.lock" <<EOF
# spool lockfile v1
# This file is generated by spool. Do not edit by hand.

[[package]]
name = 'fixture'
git = '$URL'
tag = 'v1.0.0'
rev = '$REV'
content_hash = '$TREE'

EOF
}

# Out of range (>=0.2.0): fail closed before git fetch / tag resolve / link.
# install, add, and update all apply the same check.
rm -rf "$CACHE"
OLD="$BASE/old"
write_app "$OLD" "old" "coil = \">=0.2.0\""
lock_fixture "$OLD"
export SPOOL_PROJECT="$OLD"
set +e
OUT="$("$ROOT/spool" install 2>&1)"
RC=$?
set -e
expect_fail "$OUT" "$RC" "old" ">=0.2.0"
assert_no_fetch "$OLD"
assert_hooks_idle "$OLD"

set +e
OUT="$("$ROOT/spool" add extra --path "$FIX" 2>&1)"
RC=$?
set -e
expect_fail "$OUT" "$RC" "old" ">=0.2.0"
assert_no_fetch "$OLD"
assert_hooks_idle "$OLD"

set +e
OUT="$("$ROOT/spool" update 2>&1)"
RC=$?
set -e
expect_fail "$OUT" "$RC" "old" ">=0.2.0"
assert_no_fetch "$OLD"
assert_hooks_idle "$OLD"

# ^0.2 is also out of range for 0.1.0 (caret stays within 0.2.x).
rm -rf "$CACHE"
CARET="$BASE/caret"
write_app "$CARET" "caret" "coil = \"^0.2\""
lock_fixture "$CARET"
export SPOOL_PROJECT="$CARET"
set +e
OUT="$("$ROOT/spool" install 2>&1)"
RC=$?
set -e
expect_fail "$OUT" "$RC" "caret" "^0.2"
assert_no_fetch "$CARET"
assert_hooks_idle "$CARET"

set +e
OUT="$("$ROOT/spool" add extra --path "$FIX" 2>&1)"
RC=$?
set -e
expect_fail "$OUT" "$RC" "caret" "^0.2"
assert_no_fetch "$CARET"

set +e
OUT="$("$ROOT/spool" update 2>&1)"
RC=$?
set -e
expect_fail "$OUT" "$RC" "caret" "^0.2"
assert_no_fetch "$CARET"

# Path dep constraint is visible before git (manifest already local).
PATHLIB="$BASE/pathlib"
write_lib "$PATHLIB" "pathlib" "coil = \">=0.2.0\""

PATHAPP="$BASE/pathapp"
write_app "$PATHAPP" "pathapp"
export SPOOL_PROJECT="$PATHAPP"
rm -rf "$CACHE"
set +e
OUT="$("$ROOT/spool" add pathlib --path "$PATHLIB" 2>&1)"
RC=$?
set -e
expect_fail "$OUT" "$RC" "pathlib" ">=0.2.0"
assert_no_fetch "$PATHAPP"
assert_hooks_idle "$PATHAPP"

# Newly fetched git dep: check after checkout, still no link / no hooks.
GITLIB="$BASE/gitlib"
write_lib "$GITLIB" "gitlib" "coil = \">=0.2.0\""
git init -q "$GITLIB"
git -C "$GITLIB" config user.email "spool@test"
git -C "$GITLIB" config user.name "spool"
git -C "$GITLIB" add -A
git -C "$GITLIB" commit -q -m "init"
git -C "$GITLIB" tag v1.0.0
GITURL="file://$GITLIB"

GITAPP="$BASE/gitapp"
write_app "$GITAPP" "gitapp"
export SPOOL_PROJECT="$GITAPP"
set +e
OUT="$("$ROOT/spool" add gitlib --git "$GITURL" --version "^1.0" 2>&1)"
RC=$?
set -e
expect_fail "$OUT" "$RC" "gitlib" ">=0.2.0"
assert_not_linked "$GITAPP"
assert_hooks_idle "$GITAPP"

# In-range update (same check, satisfied): install then update succeed.
rm -rf "$CACHE"
UP="$BASE/up"
write_app "$UP" "up" "coil = \">=0.1.0\""
lock_fixture "$UP"
export SPOOL_PROJECT="$UP"
"$ROOT/spool" install
test -L "$UP/.spool/deps/fixture"
assert_hooks_idle "$UP"
"$ROOT/spool" update
assert_hooks_idle "$UP"

echo "smoke_engine: ok (coil $COIL_VER)"
