#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COIL_BIN="${COIL:-coil}"
FIX="$ROOT/scratch/fixture_repo"
CACHE="$ROOT/scratch/cache"
PROJ="$ROOT/scratch/proj"

rm -rf "$FIX" "$CACHE" "$PROJ"
mkdir -p "$FIX" "$PROJ/src"

git init -q "$FIX"
git -C "$FIX" config user.email "spool@test"
git -C "$FIX" config user.name "spool"
echo "hello from fixture" > "$FIX/README.md"
mkdir -p "$FIX/src"
echo "// fixture lib" > "$FIX/src/lib.hy"
git -C "$FIX" add -A
git -C "$FIX" commit -q -m "init"
git -C "$FIX" tag v1.0.0
REV="$(git -C "$FIX" rev-parse HEAD)"
TREE="$(git -C "$FIX" rev-parse 'HEAD^{tree}')"
URL="file://$FIX"

cat > "$PROJ/coil.toml" <<EOF
[package]
name = "smoke"
version = "0.0.1"

[module]
roots = ["./src"]

[env]
allow_exec = true
EOF
echo "// consumer" > "$PROJ/src/main.hy"

cat > "$PROJ/coil.lock" <<EOF
# spool lockfile v1
# This file is generated by spool. Do not edit by hand.

[[package]]
name = 'fixture'
git = '$URL'
tag = 'v1.0.0'
rev = '$REV'
content_hash = '$TREE'

EOF

export COIL="$COIL_BIN"
export COIL_CACHE_DIR="$CACHE"
export SPOOL_PROJECT="$PROJ"
"$ROOT/spool" install

test -L "$PROJ/.spool/deps/fixture"
test -f "$PROJ/.spool/deps/fixture/README.md"
grep -q '.spool/deps' "$PROJ/coil.toml"

echo "smoke_install: ok (rev=$REV tree=$TREE)"
