#!/usr/bin/env bash
# COI-14: lock diagnostics and content-hash check.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)/.."
ROOT="$(cd "$ROOT" && pwd)"
COIL_BIN="${COIL:-coil}"
CACHE="$ROOT/scratch/cache_integrity"
FIX="$ROOT/scratch/integrity_repo"
PROJ="$ROOT/scratch/proj_integrity"
MISS="$ROOT/scratch/proj_missing_lock"

rm -rf "$CACHE" "$FIX" "$PROJ" "$MISS"
mkdir -p "$FIX/src" "$PROJ/src" "$MISS/src"

git init -q "$FIX"
git -C "$FIX" config user.email "spool@test"
git -C "$FIX" config user.name "spool"
echo "// lib" > "$FIX/src/lib.hy"
git -C "$FIX" add -A
git -C "$FIX" commit -q -m "init"
git -C "$FIX" tag v1.0.0
REV="$(git -C "$FIX" rev-parse HEAD)"
TREE="$(git -C "$FIX" rev-parse 'HEAD^{tree}')"
URL="file://$FIX"

cat > "$PROJ/coil.toml" <<EOF
[package]
name = "integrity"
version = "0.0.1"
[module]
roots = ["./src"]
[env]
allow_exec = true
EOF
echo "// app" > "$PROJ/src/main.hy"
cat > "$PROJ/coil.lock" <<EOF
# spool lockfile v1
# This file is generated by spool. Do not edit by hand.

[[package]]
name = 'fixture'
git = '$URL'
tag = 'v1.0.0'
rev = '$REV'
content_hash = '$TREE'

EOF

export COIL="$COIL_BIN"
export COIL_CACHE_DIR="$CACHE"
export SPOOL_PROJECT="$PROJ"
"$ROOT/spool" install

# Bad hash must fail closed.
sed -i "s/content_hash = '$TREE'/content_hash = 'deadbeefdeadbeefdeadbeefdeadbeefdeadbeef'/" "$PROJ/coil.lock"
set +e
OUT="$("$ROOT/spool" install 2>&1)"
RC=$?
set -e
if [[ "$RC" -eq 0 ]]; then
  echo "smoke_integrity: expected hash mismatch to fail" >&2
  exit 1
fi
echo "$OUT" | grep -q "integrity mismatch for fixture"

# Missing lock with a git dep.
cat > "$MISS/coil.toml" <<EOF
[package]
name = "missing"
version = "0.0.1"
[module]
roots = ["./src"]
[env]
allow_exec = true
[dependencies]
fixture = { git = "$URL", version = "^1.0" }
EOF
echo "// app" > "$MISS/src/main.hy"
export SPOOL_PROJECT="$MISS"
set +e
OUT="$("$ROOT/spool" install 2>&1)"
RC=$?
set -e
if [[ "$RC" -eq 0 ]]; then
  echo "smoke_integrity: expected missing lock to fail" >&2
  exit 1
fi
echo "$OUT" | grep -q "missing coil.lock"

# Corrupt lock.
echo "not a lock" > "$MISS/coil.lock"
set +e
OUT="$("$ROOT/spool" install 2>&1)"
RC=$?
set -e
if [[ "$RC" -eq 0 ]]; then
  echo "smoke_integrity: expected corrupt lock to fail" >&2
  exit 1
fi
echo "$OUT" | grep -q "corrupt coil.lock"

UNRES="$ROOT/scratch/proj_unresolved"
rm -rf "$UNRES"
mkdir -p "$UNRES/src"
cat > "$UNRES/coil.toml" <<EOF
[package]
name = "unresolved"
version = "0.0.1"
[module]
roots = ["./src"]
[env]
allow_exec = true
[dependencies]
fixture = { git = "$URL", version = "^1.0" }
EOF
echo "// app" > "$UNRES/src/main.hy"
cat > "$UNRES/coil.lock" <<'EOF'
# spool lockfile v1
# This file is generated by spool. Do not edit by hand.

EOF
export SPOOL_PROJECT="$UNRES"
set +e
OUT="$("$ROOT/spool" install 2>&1)"
RC=$?
set -e
if [[ "$RC" -eq 0 ]]; then
  echo "smoke_integrity: expected unresolved dep to fail" >&2
  exit 1
fi
echo "$OUT" | grep -q "unresolved dependency fixture"

echo "smoke_integrity: ok"
