#!/usr/bin/env bash
# COI-105: fail-closed [package].coil engine range on install/add/update.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COIL_BIN="${COIL:-coil}"
CACHE="$ROOT/scratch/cache_engine"
BASE="$ROOT/scratch/engine"

if [[ ! -x "$COIL_BIN" ]]; then
  if ! command -v "$COIL_BIN" >/dev/null 2>&1; then
    echo "smoke_engine: coil not found (set COIL)" >&2
    exit 1
  fi
fi

if ! VER_LINE="$("$COIL_BIN" --version)"; then
  echo "smoke_engine: coil --version required" >&2
  exit 1
fi
COIL_VER="${VER_LINE#coil }"
COIL_VER="${COIL_VER%%[$'\n\r']}"
if [[ -z "$COIL_VER" ]]; then
  echo "smoke_engine: could not parse coil --version ($VER_LINE)" >&2
  exit 1
fi

rm -rf "$CACHE" "$BASE"
mkdir -p "$BASE"

write_app() {
  local dest="$1"
  local name="$2"
  local coil_line="${3:-}"
  rm -rf "$dest"
  mkdir -p "$dest/src"
  cat > "$dest/coil.toml" <<EOF
[package]
name = "$name"
version = "0.0.1"
${coil_line}

[module]
roots = ["./src"]
[env]
allow_exec = true
EOF
  echo "// app" > "$dest/src/main.hy"
}

expect_fail() {
  local out="$1"
  local rc="$2"
  local pkg="$3"
  local range="$4"
  if [[ "$rc" -eq 0 ]]; then
    echo "smoke_engine: expected engine range to fail for $pkg" >&2
    echo "$out" >&2
    exit 1
  fi
  echo "$out" | grep -q "package $pkg"
  echo "$out" | grep -q "$range"
  echo "$out" | grep -q "$COIL_VER"
}

export COIL="$COIL_BIN"
export COIL_CACHE_DIR="$CACHE"

# Omitted key: install succeeds.
OMIT="$BASE/omit"
write_app "$OMIT" "omit"
export SPOOL_PROJECT="$OMIT"
"$ROOT/spool" install

# In-range: no-op success (comparison language from git-dep version).
OK="$BASE/ok"
write_app "$OK" "ok" "coil = \">=0.0.0\""
export SPOOL_PROJECT="$OK"
"$ROOT/spool" install

STAR="$BASE/star"
write_app "$STAR" "star" "coil = \"*\""
export SPOOL_PROJECT="$STAR"
"$ROOT/spool" install

# Too-old root: fail closed before git fetch.
FIX="$BASE/fixture"
mkdir -p "$FIX/src"
cat > "$FIX/coil.toml" <<'EOF'
[package]
name = "fixture"
version = "1.0.0"
[module]
roots = ["./src"]
EOF
echo "// lib" > "$FIX/src/lib.hy"
git init -q "$FIX"
git -C "$FIX" config user.email "spool@test"
git -C "$FIX" config user.name "spool"
git -C "$FIX" add -A
git -C "$FIX" commit -q -m "init"
git -C "$FIX" tag v1.0.0
REV="$(git -C "$FIX" rev-parse HEAD)"
TREE="$(git -C "$FIX" rev-parse 'HEAD^{tree}')"
URL="file://$FIX"

OLD="$BASE/old"
write_app "$OLD" "old" "coil = \">=99.0.0\""
cat >> "$OLD/coil.toml" <<EOF
[dependencies]
fixture = { git = "$URL", version = "^1.0" }
EOF
cat > "$OLD/coil.lock" <<EOF
# spool lockfile v1
# This file is generated by spool. Do not edit by hand.

[[package]]
name = 'fixture'
git = '$URL'
tag = 'v1.0.0'
rev = '$REV'
content_hash = '$TREE'

EOF
export SPOOL_PROJECT="$OLD"
set +e
OUT="$("$ROOT/spool" install 2>&1)"
RC=$?
set -e
expect_fail "$OUT" "$RC" "old" ">=99.0.0"
if [[ -d "$CACHE/git" ]]; then
  echo "smoke_engine: unsatisfied root range fetched before failing" >&2
  exit 1
fi

# add / update refuse the same root constraint.
set +e
OUT="$("$ROOT/spool" add extra --path "$FIX" 2>&1)"
RC=$?
set -e
expect_fail "$OUT" "$RC" "old" ">=99.0.0"

set +e
OUT="$("$ROOT/spool" update 2>&1)"
RC=$?
set -e
expect_fail "$OUT" "$RC" "old" ">=99.0.0"

# Path dep constraint is visible before git (manifest already local).
PATHLIB="$BASE/pathlib"
mkdir -p "$PATHLIB/src"
cat > "$PATHLIB/coil.toml" <<'EOF'
[package]
name = "pathlib"
version = "0.1.0"
coil = ">=99.0.0"
[module]
roots = ["./src"]
EOF
echo "// path lib" > "$PATHLIB/src/lib.hy"

PATHAPP="$BASE/pathapp"
write_app "$PATHAPP" "pathapp"
export SPOOL_PROJECT="$PATHAPP"
set +e
OUT="$("$ROOT/spool" add pathlib --path "$PATHLIB" 2>&1)"
RC=$?
set -e
expect_fail "$OUT" "$RC" "pathlib" ">=99.0.0"

# Newly fetched git dep: check after checkout.
GITLIB="$BASE/gitlib"
mkdir -p "$GITLIB/src"
cat > "$GITLIB/coil.toml" <<'EOF'
[package]
name = "gitlib"
version = "1.0.0"
coil = ">=99.0.0"
[module]
roots = ["./src"]
EOF
echo "// git lib" > "$GITLIB/src/lib.hy"
git init -q "$GITLIB"
git -C "$GITLIB" config user.email "spool@test"
git -C "$GITLIB" config user.name "spool"
git -C "$GITLIB" add -A
git -C "$GITLIB" commit -q -m "init"
git -C "$GITLIB" tag v1.0.0
GITURL="file://$GITLIB"

GITAPP="$BASE/gitapp"
write_app "$GITAPP" "gitapp"
export SPOOL_PROJECT="$GITAPP"
set +e
OUT="$("$ROOT/spool" add gitlib --git "$GITURL" --version "^1.0" 2>&1)"
RC=$?
set -e
expect_fail "$OUT" "$RC" "gitlib" ">=99.0.0"

echo "smoke_engine: ok (coil $COIL_VER)"
