// coil.lock read/write - deterministic spool lockfile format.
// Packages are carried as tab-separated records:
//   name \t git \t tag \t rev \t content_hash
use text::{trim, starts_with, split, contains, ends_with, slice, join as text_join};
use io::file::{read_text, write_text};
use io::fs::{exists};
use string::{format, to_bytes};

fn make_git_pkg(string name, string git, string tag, string rev, string hash) -> string {
    return name + "\t" + git + "\t" + tag + "\t" + rev + "\t" + hash;
}

fn field_at(string p, int idx) -> string {
    let parts = match split(p, "\t") {
        Result::Ok(v) => v,
        Result::Err(_) => {
            let empty: Vec<string> = Vec::new();
            empty
        },
    };
    if idx < len(parts) {
        return parts[idx];
    }
    return "";
}

fn lock_pkg_name(string p) -> string {
    return field_at(p, 0);
}

fn lock_pkg_git(string p) -> string {
    return field_at(p, 1);
}

fn lock_pkg_tag(string p) -> string {
    return field_at(p, 2);
}

fn lock_pkg_rev(string p) -> string {
    return field_at(p, 3);
}

fn lock_pkg_hash(string p) -> string {
    return field_at(p, 4);
}

fn lock_git_url(string p) -> string {
    return lock_pkg_git(p);
}

fn lock_git_rev(string p) -> string {
    return lock_pkg_rev(p);
}

fn lock_git_hash(string p) -> string {
    return lock_pkg_hash(p);
}

fn quote(string s) -> string {
    return "'" + s + "'";
}

fn strip_quotes(string s) -> string {
    let t = match trim(s) {
        Result::Ok(x) => x,
        Result::Err(_) => s,
    };
    if len(t) >= 2 {
        if starts_with(t, "'") {
            if ends_with(t, "'") {
                return match slice(t, 1, len(t) - 1) {
                    Result::Ok(inner) => inner,
                    Result::Err(_) => t,
                };
            }
        }
        if starts_with(t, "\"") {
            if ends_with(t, "\"") {
                return match slice(t, 1, len(t) - 1) {
                    Result::Ok(inner) => inner,
                    Result::Err(_) => t,
                };
            }
        }
    }
    return t;
}

fn parse_kv_line(string line) -> Result<(string, string), string> {
    if contains(line, "=") == false {
        raise "expected key = value";
    }
    let parts = match split(line, "=") {
        Result::Ok(p) => p,
        Result::Err(_) => raise "split failed",
    };
    if len(parts) < 2 {
        raise "expected key = value";
    }
    let key = match trim(parts[0]) {
        Result::Ok(t) => t,
        Result::Err(_) => parts[0],
    };
    let rhs = parts[1];
    let i = 2;
    while i < len(parts) {
        rhs = rhs + "=" + parts[i];
        i = i + 1;
    }
    return (key, strip_quotes(rhs));
}

fn cmp_str(string a, string b) -> int {
    if a == b {
        return 0;
    }
    let ab = to_bytes(a);
    let bb = to_bytes(b);
    let i = 0;
    let lim = len(ab);
    if len(bb) < lim {
        lim = len(bb);
    }
    while i < lim {
        if ab[i] < bb[i] {
            return 0 - 1;
        }
        if ab[i] > bb[i] {
            return 1;
        }
        i = i + 1;
    }
    if len(ab) < len(bb) {
        return 0 - 1;
    }
    if len(ab) > len(bb) {
        return 1;
    }
    return 0;
}

fn sort_packages(Vec<string> packages) -> Vec<string> {
    let out: Vec<string> = Vec::new();
    let i = 0;
    while i < len(packages) {
        out.push(packages[i]);
        i = i + 1;
    }
    let n = len(out);
    let a = 1;
    while a < n {
        let j = a;
        while j > 0 {
            if cmp_str(lock_pkg_name(out[j - 1]), lock_pkg_name(out[j])) <= 0 {
                break;
            }
            let tmp = out[j - 1];
            out[j - 1] = out[j];
            out[j] = tmp;
            j = j - 1;
        }
        a = a + 1;
    }
    return out;
}

fn lock_serialize(Vec<string> packages) -> string {
    let sorted = sort_packages(packages);
    let out = "# spool lockfile v1
# This file is generated by spool. Do not edit by hand.

";
    let i = 0;
    while i < len(sorted) {
        let p = sorted[i];
        i = i + 1;
        out = out + "[[package]]
";
        out = out + "name = " + quote(lock_pkg_name(p)) + "
";
        out = out + "git = " + quote(lock_pkg_git(p)) + "
";
        out = out + "tag = " + quote(lock_pkg_tag(p)) + "
";
        out = out + "rev = " + quote(lock_pkg_rev(p)) + "
";
        out = out + "content_hash = " + quote(lock_pkg_hash(p)) + "

";
    }
    return out;
}

fn finish_pkg(string name, string git, string tag, string rev, string hash) -> Result<string, string> {
    if len(name) == 0 {
        raise "package missing name";
    }
    if len(git) == 0 {
        raise "package missing git";
    }
    if len(rev) == 0 {
        raise "package missing rev";
    }
    if len(hash) == 0 {
        raise "package missing content_hash";
    }
    return make_git_pkg(name, git, tag, rev, hash);
}

fn lock_parse(string source) -> Result<Vec<string>, string> {
    let lines = match split(source, "\n") {
        Result::Ok(ls) => ls,
        Result::Err(_) => raise "split lock failed",
    };
    let out: Vec<string> = Vec::new();
    let in_pkg = false;
    let name = "";
    let git = "";
    let tag = "";
    let rev = "";
    let hash = "";
    let i = 0;

    while i < len(lines) {
        let line = match trim(lines[i]) {
            Result::Ok(t) => t,
            Result::Err(_) => lines[i],
        };
        i = i + 1;
        if len(line) == 0 {
            continue;
        }
        if starts_with(line, "#") {
            continue;
        }
        if line == "[[package]]" {
            if in_pkg {
                let pkg = finish_pkg(name, git, tag, rev, hash)?;
                out.push(pkg);
            }
            in_pkg = true;
            name = "";
            git = "";
            tag = "";
            rev = "";
            hash = "";
            continue;
        }
        if in_pkg == false {
            raise format("unexpected lock line: %s", line);
        }
        let kv = parse_kv_line(line)?;
        let (k, v) = kv;
        if k == "name" {
            name = v;
        } else {
            if k == "git" {
                git = v;
            } else {
                if k == "tag" {
                    tag = v;
                } else {
                    if k == "rev" {
                        rev = v;
                    } else {
                        if k == "content_hash" {
                            hash = v;
                        } else {
                            raise format("unknown lock key %s", k);
                        }
                    }
                }
            }
        }
    }
    if in_pkg {
        let pkg = finish_pkg(name, git, tag, rev, hash)?;
        out.push(pkg);
    }
    return out;
}

fn lock_write(string path, Vec<string> packages) -> Result<int, string> {
    let body = lock_serialize(packages);
    return match write_text(path, body) {
        Result::Ok(_) => 0,
        Result::Err(_) => raise format("failed to write %s", path),
    };
}

fn lock_read(string path) -> Result<Vec<string>, string> {
    let body = match read_text(path) {
        Result::Ok(s) => s,
        Result::Err(_) => raise format("failed to read %s", path),
    };
    return lock_parse(body)?;
}

fn lock_read_or_empty(string path) -> Result<Vec<string>, string> {
    let present = match exists(path) {
        Result::Ok(v) => v,
        Result::Err(_) => false,
    };
    if present == false {
        let empty: Vec<string> = Vec::new();
        return empty;
    }
    return lock_read(path)?;
}

fn lock_upsert(Vec<string> packages, string pkg) -> Vec<string> {
    let name = lock_pkg_name(pkg);
    let out: Vec<string> = Vec::new();
    let i = 0;
    while i < len(packages) {
        if lock_pkg_name(packages[i]) != name {
            out.push(packages[i]);
        }
        i = i + 1;
    }
    out.push(pkg);
    return out;
}

fn lock_hashes_match(Vec<string> packages, Vec<(string, string)> expected) -> bool {
    let i = 0;
    while i < len(packages) {
        let p = packages[i];
        i = i + 1;
        let n = lock_pkg_name(p);
        let h = lock_pkg_hash(p);
        let found = false;
        let j = 0;
        while j < len(expected) {
            let (en, eh) = expected[j];
            if en == n {
                found = true;
                if eh != h {
                    return false;
                }
            }
            j = j + 1;
        }
        if found == false {
            return false;
        }
    }
    return true;
}
